export const USE_24_HOURS_KEY = "USE24HOURSKEY";
export const IS_STOPWATCH_ON_KEY = "ISSTOPWATCHONKEY";
export const STOPWATCH_START_TIME_KEY = "STOPWATCHSTARTTIMEKEY";
export const STOPWATCH_SECONDS_KEY = "STOPWATCHSECONDSKEY";